### ISSUE TITLE
Conda-forge package maintainers

### ISSUE THREAD

**Issue by Zeitsperre** [usbr/ostrich#30]
Hi there, I wanted to let the developers know that I'm currently in the process of contributing Ostrich to the `conda-forge` ecosystem (see: https://github.com/conda-forge/staged-recipes/pull/14684).

@Julemai and I are listed as maintainers currently, but I wanted to see if the other package developers would want to be included (I don't use Ostrich, but some projects I build/maintain do). Maintenance is very simple; tagged versions from git can be updated in no time at all and the benefit is a conda-installable pre-compiled binary.

**Would anyone want to be included on the maintainers list?** Please let me know!

As an aside, the maintainers are interested in the potential to integrate `make` tests down-the-line. Perhaps a bit more pressure for #4.

**Comment by lsmatott** [comment]
Yes please!



From: Trevor James Smith ***@***.***>
Sent: Thursday, May 6, 2021 10:16 AM
To: usbr/ostrich ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usbr/ostrich] Conda-forge package maintainers (#30)


Hi there, I wanted to let the developers know that I'm currently in the process of contributing Ostrich to the conda-forge ecosystem (see: conda-forge/staged-recipes#14684<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconda-forge%2Fstaged-recipes%2Fpull%2F14684&data=04%7C01%7Clsmatott%40buffalo.edu%7C82cbb0ad1ba94995c8e808d9109971f7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637559073513337445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HI39IgwD4hpmOVkwuT5FxwO79W2hcN6%2Fua1xjCTvKjw%3D&reserved=0>).

@julemai<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjulemai&data=04%7C01%7Clsmatott%40buffalo.edu%7C82cbb0ad1ba94995c8e808d9109971f7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637559073513337445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Te5QF1BjiB6LzGQ9DT8%2FkexezS1cGpSskcB2GLO25Ps%3D&reserved=0> and I are listed as maintainers currently, but I wanted to see if the other package developers would want to be included (I don't use Ostrich, but some projects I build/maintain do). Maintenance is very simple; tagged versions from git can be updated in no time at all and the benefit is a conda-installable pre-compiled binary.

Would anyone want to be included on the maintainers list? Please let me know!

As an aside, the maintainers are interested in the potential to integrate make tests down-the-line. Perhaps a bit more pressure for #4<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusbr%2Fostrich%2Fissues%2F4&data=04%7C01%7Clsmatott%40buffalo.edu%7C82cbb0ad1ba94995c8e808d9109971f7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637559073513347440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=waiopLy5P1fURk%2F0BLU9lvzByJ48NxPEFnWEUNB9GnY%3D&reserved=0>.

-

**Comment by dloney** [comment]
Please add me as well. I'm in the process of reworking the MPI structure to remove broadcasts. That will eventually make the entire structure much more efficient and scalable. It might be good to roll out the tests as I'm migrating over each algorithm to the new compute engine.

**Comment by Zeitsperre** [comment]
Sounds good, I've tagged you both on the PR. I just need an ok message or :+1: on my post before the conda-forge crew will merge it. All the best!

**Comment by lsmatott** [comment]
Ok - I thumbs-upped a bunch of posts. Let me know if I got the right one ;)
