### ISSUE TITLE
Makefile or CMake recipe for Windows?

### ISSUE THREAD

**Issue by Zeitsperre** [usbr/ostrich#42]
Hi there,

I've been working on a build of Ostrich for Windows on conda-forge (https://github.com/conda-forge/ostrich-feedstock/pull/2) and have run into some difficulties. If it's possible, I would like to know the following:
 - If one were to replace the `gcc` calls with `cl.exe`, does the Makefile on this repo currently support Windows (Cygwin)?
   - The documentation mentions the need for MPI when building on Windows, so am I safe in assuming that the `GCC_MPI` is the recipe that should be used? 
- I keep getting errors about msado15.dll when building this library (full stack trace [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=466716&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=432)), any advice for dealing with this? Is this DLL bundled with something or need to be loaded more explicitly?

In the case that my approach is not compatible with Windows (ie: the Makefile does not support Windows), would it be possible for someone to generate a CMakeLists.txt for the last Ostrich release (i.e.: https://github.com/usbr/ostrich/releases/tag/v21.03.16)? This would help me out immensely (and would probably be much faster than patching the Makefile).

Thanks,

**Comment by Zeitsperre** [comment]
Hi Shawn, thanks for the response and the advice.

To give you a very quick overview, I have Ostrich _nearly_ building in a dockerized environment with VC++, except for the calls to this Microsoft ActiveX Data Objects library. I do however have the option of setting the runtime to use MinGW with GCC, so I'll see if I can get it working with the GCC compiler. If this works, we'll have Windows builds for Ostrich installable via Anaconda!

**Comment by lsmatott** [comment]
Hi Trevor,

The msado library is needed for optional Access database integration ... it is for supporting models that store their output in Access databases. It may be simplest to just stub out the relevant code using an #ifdef ....

The relevant files are:

ADOConnection.cpp
ADOConnection.h

The code currently uses _WIN32 to include/exclude the ADO functionality. You could add some #ifdef logic .... Something like the following ....

#ifdef _WIN32
  #ifndef WIN32_DOCKER
    /* import the dll, etc */
  #else
    /* not supported, use Linux stubs */
  #endif
#else
    /* not supported, use Linux stubs */
#endif

**Comment by dloney** [comment]
Hi Trevor, 
Another option is to do the build against the dev branch. Right now the functionality is reduced, but the build should be platform independent. It depends on what algorithms you want access to. Right now it has coverage of the GA and LM methods.

**Comment by Zeitsperre** [comment]
I can't say for sure what we need for our projects (I only package and maintain), but I think the plan is for @julemai and I to tackle this together next month. Thanks again for all the help!

**Comment by julemai** [comment]
What we mainly need is DDS and SCE in this project. But I guess we can also implement @lsmatott's suggestion above to make it a clean implementation? Or is the "msado" functionality supposed to go away?
